#!/usr/bin/env bash
# Purpose - Export a man page to various file formats
# Example name: export_man
# Usage: export_man bash
# Files output:
#   Man_bash.pandoc.html5.html
#   Man_bash.pandoc.html.html
#   Man_bash.groff.html
#   Man_bash.manly.html
#   Man_bash.man.troff.ps
#   Man_bash.gs.pdf
#   Man_bash.gs.inverted.pdf

# Deps manly gs pandoc zcat
# git clone https://gitlab.com/es20490446e/manly.git
# cd manly && ./install-uninstall.sh

Text_File_Output_Lines_Length=3000
Open_Text_File_Output_With=codium
ManualToRetrieve="$1"
SaveDir="$HOME/Documents/Manuals/"
FilenamesPrefix="Man_"

if [ ! -d "$SaveDir" ]; then
    mkdir $SaveDir
fi

Man_Filepath="$(man --path "$1")"
output_text_file="$SaveDir$FilenamesPrefix$ManualToRetrieve.txt"

MANWIDTH=$Text_File_Output_Lines_Length man $ManualToRetrieve | col -bx > "$output_text_file" && $Open_Text_File_Output_With "$output_text_file"
pandoc --from man --to html5 <<< "$(zcat "$Man_Filepath")" > "$SaveDir""$FilenamesPrefix""$1".pandoc.html5.html
pandoc --from man --to html <<< "$(zcat "$Man_Filepath")" > "$SaveDir""$FilenamesPrefix""$1".pandoc.html.html
zcat "$Man_Filepath"  | groff -mandoc -Thtml >"$SaveDir""$FilenamesPrefix""$1".groff.html
zcat "$Man_Filepath" | manly >"$SaveDir""$FilenamesPrefix""$1".manly.html
man --troff "$1" >"$SaveDir""$FilenamesPrefix""$1".man.troff.ps

gs -o "$SaveDir""$FilenamesPrefix""$1".gs.pdf -sDEVICE=pdfwrite -f "$SaveDir""$FilenamesPrefix""$1".man.troff.ps

perl -pe 's/%!PS-Adobe-3.0 Resource-ProcSet\K/\n\{1 exch sub\} settransfer/gm' <"$SaveDir""$FilenamesPrefix""$1".man.troff.ps >"$SaveDir""$FilenamesPrefix""$1".man.troff.inverted.ps

gs -o "$SaveDir""$FilenamesPrefix""$1".gs.inverted.pdf -sDEVICE=pdfwrite -f "$SaveDir""$FilenamesPrefix""$1".man.troff.inverted.ps

echo ""
echo ""
echo "$output_text_file"
echo "$SaveDir""$FilenamesPrefix""$1".pandoc.html5.html
echo "$SaveDir""$FilenamesPrefix""$1".pandoc.html.html
echo "$SaveDir""$FilenamesPrefix""$1".groff.html
echo "$SaveDir""$FilenamesPrefix""$1".manly.html
echo "$SaveDir""$FilenamesPrefix""$1".man.troff.ps
echo "$SaveDir""$FilenamesPrefix""$1".gs.pdf
echo "$SaveDir""$FilenamesPrefix""$1".gs.inverted.pdf
