#!/usr/bin/env bash
# Return mpv watch history newest to oldest. Need line "write-filename-in-watch-later-config=yes" in mpv.conf

watch_later_dir='/home/jjenkx/.config/mpv/watch_later/'
how_many_to_return=1000
cat $(find "$watch_later_dir" -type f -printf "%T@ %p\n" \
| sort \
| cut -c23- \
| tail -$how_many_to_return) \
\
| perl -0777 -pe 's/^[^#].*\n|# (.+\/)(.*)/'\''$1$2'\''\n$2/gm' \
| rg \
    --colors 'match:none' \
    --colors 'match:fg:0,200,0' \
    --colors 'match:bg:0,0,0' \
    --colors 'match:style:bold' \
    -B1 -P "^[^'\/].*" 
