#!/usr/bin/env bash

# Set the directory where you want to remove text files
watch_later_dir="$HOME/.config/mpv/watch_later/"

# List the four newest text files in the directory
newest_files=$(ls -t "$watch_later_dir"/* 2>/dev/null | head -n 4)

# Iterate through the four newest text files
for file in $newest_files; do
    # Check if the file exists and is a regular file
    if [ -f "$file" ]; then
        # Check if the first line of the file starts with "# redirect entry"
        if head -n 1 "$file" | grep -q "^# redirect entry"; then
            # Remove the file if the condition is met
            rm "$file"
        fi
    fi
done


setsid >/dev/null 2>&1 </dev/null \
mpv "$(cat $(echo /home/jjenkx/.config/mpv/watch_later/$(eza --color=never -1 --reverse -s modified /home/jjenkx/.config/mpv/watch_later/ | head -1)) | head -1 | cut -c3-)" \
2>&1 >/dev/null & 
