#!/usr/bin/env bash
# Deps
# sudo pacman -S --needed wireguard-tools
# Must run mullvadbenchmark before this script will work. This connects to fastest speedtest vpn server by reading output file from https://github.com/JJenkx/Personal/blob/main/mullvadbenchmark

cat /home/jjenkx/Documents/fast-cli.results | perl -0777 -pe 's/\n(?!\/)//gm' | awk -F': ' '/downloadSpeed/ {print $2 " " $0}' | sort -nr | cut -d' ' -f2-
echo

fastest="$(  cat /home/jjenkx/Documents/fast-cli.results | perl -0777 -pe 's/\n(?!\/)//gm' | awk -F': ' '/downloadSpeed/ {print $2 " " $0}' | sort -nr | cut -d' ' -f2- | grep -oE '/etc/wireguard/[^{]*'  )"
echo "The fastest servers from fastest to slowest are:"
cat <<< "$fastest"

SAVEIFS=$IFS
IFS=$'\n'
fastest=($fastest)
IFS=$SAVEIFS

first_server="${fastest[0]}"

sudo wg-quick up "$first_server"
